### ISSUE TITLE
Generate GX conformant credentials for VM Images  

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/gx-credential-generator#67]
### Motivation 

As a potential _cloud customer_, I want to know what VM (virtual machine) images are provided by a SCS cloud service provider. Gaia-X provides special class [VM_Image](https://gitlab.com/gaia-x/technical-committee/service-characteristics/-/blob/262-transform-virtual-machine-service-offering-to-linkml/single-point-of-truth/22.10/vm-image.yaml) to describe offered VM Images as temper-evident Gaia-X Credential.

### Task
Write/Update script to generate Gaia-X Credentials for VM Images. 

The following Gaia-X Image properties **MUST** be generated:

- [x] copyrightOwnedBy
- [x] license
- [x] resourcePolicy

The following Gaia-X Image properties  **SHOULD** be generated:

- [x] operatingSystem 
- [x] cpuReq
- [x] ramReq
- [x] rootDiskReq
- [x] updateStrategy
- [x] licenseIncluded
- [x] maintenance
- [x] buildDate

The following Gaia-X Image properties  **MAY** be generated:

- [x] name
- [x] description
- [x] aggregationOfResources
- [x] checksum
- [x] signature
- [x] version
- [x] patchLevel
- [x] fileSize
- [ ] ~gpuReq~ - not yet supported by OpenStack. See https://github.com/SovereignCloudStack/gx-credential-generator/issues/67#issuecomment-1866268946
- [x] videoRamSize
- [ ] ~encryption~ - not yet supported by OpenStack, see https://github.com/SovereignCloudStack/gx-credential-generator/issues/67#issuecomment-1864402348
- [x] secureBoot
- [x] vPMU
- [x] multiQueues
- [ ] ~hwRngTypeOfImage~ - _information provided in image metadata is not sufficient/compatible with Gaia-X_ see  https://github.com/SovereignCloudStack/gx-credential-generator/issues/67#issuecomment-1860325309
- [x] firmwareType
- [x] watcdogAction  

### Prerequisites

- Issue #66

**Comment by anjastrunk** [comment]
We need a bunch of classes, such as CPU, GPU, Memory, Disk, Cryptography, ... to create valid Gaia-X Credentials in JSON-LD. We can create these python classes manually, which is error-prone and cause a huge maintenance overhead. We have to adapt classes are every change of Gaia-X Credential schema. A better way, would be to read OWL ontology of Gaia-X Credential schema and generate python classes automatically. There are python lib, which do this work for use...

**[owlready2](https://owlready2.readthedocs.io/en/latest/)**
owlready2 ready ontology in the following format: RDF/XML, OWL/XML, NTriples. Gaia-X offers its ontology for Credential Schema on turtle format.  I convert turtle to RDF/XML, via online converter and played around with owlread2 to create instances of classes defined in ontology and write there instances as JSON-LD file. IMO: owlready2 does not very convenient in writing instances in JSON-LD. 

**[rdflib](https://rdflib.readthedocs.io/en/stable/)**:

RDF writes instances in terms of tuples, which is also not very convenient. It does not provide python classes.

**Comment by anjastrunk** [comment]
There is a challenge with Gaia-X mandatory attributes for Images. As VM Image is a sub-class of a Virtual Resource, it inherits the mandatory attributes `copyrightOwnedBy`, `license` and `resourcePolicy`. These properties are neither describe by SCS Image standards nor by any other Openstack Images metadata. Furthermore each image is a collection of software components and SHOULD (at least in the sense of Gaia-X of transparency and trustworthiness) modeled as a resource composition, where each software package is describes as a separate Software Resource with its own license, copyright owner and resource policy.  IMO, it is not reasonable for providers to do so. The same applies to Operating Systems, which is a mandatory property of each Gaia-X VM Image. 


To support Gaia-X Credentials for OpenStack images, I decided to provide the minimal required information, which is  `copyrightOwnedBy`, `license` and `resourcePolicy` for VM Image and  `copyrightOwnedBy`, `license` and `resourcePolicy` for imgae's operating system. As this information could not retrieved from OpenStack, I add some default information, within a configuration file, called `image_props.yaml`. This file can be adapted by providers.

**Comment by anjastrunk** [comment]
Is was a hard job to figure out default values for right owner and license of all operation systems. And as I'm not a legal expert, I do not know, if I did everything correctly. The default values can be found in [config/config.yaml](https://github.com/SovereignCloudStack/gx-credential-generator/blob/67-make-generation-of-vm-image-credentuial-gaia-x-compliant/config/config.yaml).

**Comment by anjastrunk** [comment]
`Copyright owner` and `license` for operating systems should be publicly available. We can put this values as default values in a configuration file.  This file can be adapted by providers with more precise information. For `resource policy`, we can use Gaia-X default policy "`allow: default`.

**Comment by anjastrunk** [comment]
Is was a hard job to figure out default values for right owner and license of all operation systems. And as I'm not a legal expert, I do not know, if I did everything correctly. The default values, available in [config/config.yaml](https://github.com/SovereignCloudStack/gx-credential-generator/blob/67-make-generation-of-vm-image-credentuial-gaia-x-compliant/config/config.yaml), should be reviewed by an expert, definitely.

**Comment by anjastrunk** [comment]
For VM images, I decided to use the following strategy for default values of the following attributes:
- `copyright owner`: Use the copyright owner of the image's operating system
- `license`: Use the license of the image's operating system
- `resource policy`: Use Gaia-X default policy `allow: default'`

To adapt these values to more precise ones, providers can change generator's configuration file.

**Comment by anjastrunk** [comment]
### Random-number generator device '"hwRngTypeOfImage"

Gaia-X supports the following values for random-number generator: Electrical noise, Chaos-based, Free-running oscillators, Quantum, and None. In contrast to that, [Openstack Image metadata](https://docs.openstack.org/glance/latest//admin/useful-image-properties) allows `libvvirt` and `others` as values to specify random number generator devices. OpenStack values and Gaia-X values does not fit. Furthermore, even image prefers a specific random-number generator there is no guarantee, instances will have on, as availability of a random-number generator depends on nova configuration. Hence, discovering random-number generator devices from OpenStack does not create any value added and I skip this property.

**Comment by anjastrunk** [comment]
OpenStack does not yet support image encryption. There is a [spec](https://specs.openstack.org/openstack/cinder-specs/specs/zed/image-encryption.html) regarding encryption, but not feature update yet. We will ski this attribute in generator.

**Comment by anjastrunk** [comment]
OpenStack does not yet support to define GPU requirements, like it is possible for CPU (e.g. architecture, number of cores, number of thread, ...)   . Hence, generator will skip generation of GPU requirements.

**Comment by anjastrunk** [comment]
GX Credentials are serialized in JSON-LD. In doing so, we use `json.dumps()` from python library [json](https://docs.python.org/3/library/json.html). This method creates JSON strings by default. To support JSON-LD, we have to implement our own call back function, which is done with `to_json_ld` in [generator.common.json_ld.py](https://github.com/SovereignCloudStack/gx-credential-generator/blob/67-make-generation-of-vm-image-credentuial-gaia-x-compliant/generator/common/json_ld.py#L59). To change  `json.dumps()` default callback method use parameter `default`.

**Comment by anjastrunk** [comment]
Data type of many attributes in GX Credential Schema are unions of types. GX Credential Schema is described with linkML. LinkML defines attribute's data type with key word `range`. To define union, `range` is skipped and key word `any_of` is used. Attribute `lisence` e.g. in class `VirtualResource` uses `any_of` to define data type as union of URI and a fixed set of [SPDX](https://spdx.org/licenses/) identifiers (as enumeration):

```yaml
class VirtualResource:
  ...
  attributes:
     license:
            required: true
            multivalued: true
            description: A list of SPDX identifiers or URL to document.
            any_of:
              - range: SPDX
              - range: uri
     ...
```
We use LinkMLs python generator to convert yaml files into python classes. However, LinkML's python generator does not evaluate key word `any_of`. All properties defined as unions, via key word `any_of` are mapped to strings. E.g. Attribute `license` is in class `VirtualResouce` is mapped to `Union[str, List[str]]` (`Union` because, `license` maximum cardinality is unlimited). Hence, we loose data type information here, which cause problems in JSON-LD serialization. As SHACL (= compliance rules for GX Credenial instance) expect `license` to be URI or SPDX identifier, all credentials generated by SCS GX Credential generator will fail. The correct data type of `license` would be `Union[Union[str, URI]], List[Union[str, URI]]]`

Missing consideration of keyword `any_of` is a bug in linkML. We can build a workaround in SCS generator, by e.g. hard coding generation of data types in JSON-LD serialization of attributes (see method `to_json_ld()` in [generator.common.json_ld.py](https://github.com/SovereignCloudStack/gx-credential-generator/blob/67-make-generation-of-vm-image-credentuial-gaia-x-compliant/generator/common/json_ld.py#L59), whose data type is defined as union. IMO, this solution will not scale. We need to manually change implementation of `to_json_ld` every time, attributes data type changes.That's why I decided to fix the bug in linkML directly. Its just a few lines of code.

**Comment by anjastrunk** [comment]
> Data type of many attributes in GX Credential Schema are unions of types. GX Credential Schema is described with linkML. LinkML defines attribute's data type with key word `range`. To define union, `range` is skipped and key word `any_of` is used. Attribute `lisence` e.g. in class `VirtualResource` uses `any_of` to define data type as union of URI and a fixed set of [SPDX](https://spdx.org/licenses/) identifiers (as enumeration):
> 
> ```yaml
> class VirtualResource:
>   ...
>   attributes:
>      license:
>             required: true
>             multivalued: true
>             description: A list of SPDX identifiers or URL to document.
>             any_of:
>               - range: SPDX
>               - range: uri
>      ...
> ```
> 
> We use LinkMLs python generator to convert yaml files into python classes. However, LinkML's python generator does not evaluate key word `any_of`. All properties defined as unions, via key word `any_of` are mapped to strings. E.g. Attribute `license` is in class `VirtualResouce` is mapped to `Union[str, List[str]]` (`Union` because, `license` maximum cardinality is unlimited). Hence, we loose data type information here, which cause problems in JSON-LD serialization. As SHACL (= compliance rules for GX Credenial instance) expect `license` to be URI or SPDX identifier, all credentials generated by SCS GX Credential generator will fail. The correct data type of `license` would be `Union[Union[str, URI]], List[Union[str, URI]]]`
> 
> Missing consideration of keyword `any_of` is a bug in linkML. We can build a workaround in SCS generator, by e.g. hard coding generation of data types in JSON-LD serialization of attributes (see method `to_json_ld()` in [generator.common.json_ld.py](https://github.com/SovereignCloudStack/gx-credential-generator/blob/67-make-generation-of-vm-image-credentuial-gaia-x-compliant/generator/common/json_ld.py#L59), whose data type is defined as union. IMO, this solution will not scale. We need to manually change implementation of `to_json_ld` every time, attributes data type changes.That's why I decided to fix the bug in linkML directly. Its just a few lines of code.

I have to correct myself. Looking deeper in to linkML's source code and playing around, I figured out: Supporting keyword `any_of` is not just a few lines of code. While changing class attribute's type is pretty simple, we also have to change class's constructor, which is a more extensive task. ...

**Comment by anjastrunk** [comment]
## aggregationOfResources

Gaia-X support to describe VM images in more detail by property `aggregationOfResources`. This attribute refers a list Gaia-X resources describing resources, VM image is based on. Gaia-X identifies entities via DID. Hence, `aggregationOfResources` contains a list of DIDs. As Openstack does not support this information, I outsourced the aggregation of resources in GX Credential Generartor's configuration file.

**Comment by anjastrunk** [comment]
## Hardware Random Number Generator (hw_rng_mode)
