### ISSUE TITLE
 Generate GX conformant credentials for Server Flavors

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/gx-credential-generator#77]
### User Story

As a potential _cloud customer_, I want to know what server flavors are provided by a SCS cloud service provider. Gaia-X provides special class [Server Flavor](https://gitlab.com/gaia-x/technical-committee/service-characteristics/-/blob/develop/single-point-of-truth/server-flavor.yaml) to describe offered server flavors as temper-evident Gaia-X Credential.

### Tasks

The following the Gaia-X server flavor properties **MUST** be generated:

- [x] cpu
- [x] ram
- [x] bootvolume

The following the Gaia-X server flavor properties **MAY** be generated:

- [x] name
- [x] description
- [x] hypervisor - https://github.com/SovereignCloudStack/gx-credential-generator/issues/77#issuecomment-1985548076
- [x] additionalVolume
- [ ] ~confidentialComputing~ - Flavor Naming Standard does not contain this information
- [x] hardwareAssistedVirtualization
- [ ] ~hwRngTypeOfFlavor~ - Flavor Naming Standard does not contain this information

### Prerequisites

- Issue #63

**Comment by anjastrunk** [comment]
# Hypervisor

We have a similar challenge with the definition of hypervisor used by a certain flavor, like we had it for images (see https://github.com/SovereignCloudStack/gx-credential-generator/issues/67#issuecomment-1860316914) Gaia-X models hypervisor as SoftwareResource, which requires mandatory attribute `copyrightOwnedby` and `license`. Both attributes are neither encoded in flavor's name nor in any other attribute. Hence, I will follow the same way as I did it for Image, I will add these information in generator's configuration file.
